### PR TITLE
[ doc ] Fixed unreachable links

### PR DESCRIPTION
**Pull request by anqur**

### CODE REVIEW

**Review by ice1000 — CHANGES_REQUESTED** [review]
Could you please instead use this syntax?
https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md#additions-to-the-documentation-syntax

**Comment by anqur** [comment]
Currently lacking an environment for verifying my change.  Advice wanted tho.

**Comment by ice1000** [comment]
> Currently lacking an environment for verifying my change.  Advice wanted tho.

Wrong syntax, you may want `crate::syntax::...`

**Comment by anqur** [comment]
> > Currently lacking an environment for verifying my change.  Advice wanted tho.
> 
> Wrong syntax, you may want `crate::syntax::...`

Literally crying...

**Review by ice1000 — APPROVED** [review]

**Comment by ice1000** [comment]
Too many commits, squashing.

**Pull request merged**
